name: publish

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: # gcp project id
  GAR_LOCATION: # for artifact registry use ex. asia-southeast1
  REPOSITORY: # artifact registry repo name
  SERVICE: # cloud run service name under your project
  REGION: # service runs on which region ex. asia-southeast1
  PROJECT_ENV: prod # set the env for the app.

jobs:
  backend:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Production Code
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.CREDENTIALS }}

      ## artifact registry auth setup
      - name: Docker auth
        id: docker-auth
        uses: docker/login-action@v1
        with:
          registry: ${{ env.GAR_LOCATION }}-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.CREDENTIALS }}

      - name: Docker build backend
        run: docker build -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}" ./

      - name: Docker push backend
        run: docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}"

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          env_vars: |
            PROJECTENV=${{ env.PROJECT_ENV }}
          image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}

      - name: Allow public access
        id: unauthenticated
        run: gcloud run services add-iam-policy-binding ${{ env.SERVICE }} --region=${{ env.REGION }} --member="allUsers" --role="roles/run.invoker"

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}